/**
 * Deterministic UX validator (Part C). Builds the canonical graph, optionally executes UX
 * scenarios and visual checks, runs every rule module, and produces a traceable, deterministically
 * ordered report. Heuristic (LLM-sourced) findings are never generated here — they can only be
 * merged in by the caller via `heuristicFindings`, and can never influence a 'fail' verdict.
 */
import type { LcdBitmapProject } from '../../domain/project';
import type { LanguageCode } from '../../domain/localization';
import { hasPathTo, initialStateIds } from './uxGraphAlgorithms';
import { buildProjectUxGraph, type ProjectUxGraph } from './uxGraphBuilder';
import { evaluateNavigationRules } from './uxRules/navigationRules';
import { evaluateSafetyRules } from './uxRules/safetyRules';
import { evaluateScenarioRules } from './uxRules/scenarioRules';
import { evaluateSemanticsRules } from './uxRules/semanticsRules';
import { evaluateStructureRules } from './uxRules/structureRules';
import { runUxScenario, type UxScenarioResult } from './uxScenarioRunner';
import { sortFindings, type UxValidationFinding } from './uxTypes';
import { evaluateVisualChecks } from './uxVisualChecks';

export interface ProjectUxAnalysisOptions {
  locale?: LanguageCode;
  includeScenarioExecution?: boolean;
  scenarioIds?: string[];
  includeVisualChecks?: boolean;
  /** Previously-imported heuristic findings to merge in (see import_project_ux_review). Never
   *  generated by this function and never allowed to affect the 'fail' verdict. */
  heuristicFindings?: UxValidationFinding[];
}

export interface UxCoverageMetric {
  covered: number;
  total: number;
}

export interface ProjectUxAnalysisReport {
  version: 1;
  verdict: 'pass' | 'needs_review' | 'fail';
  generatedAt: string;
  summary: {
    errors: number;
    warnings: number;
    infos: number;
    suggestions: number;
    needsHumanReview: number;
  };
  coverage: {
    screensWithRole: UxCoverageMetric;
    statesWithPurpose: UxCoverageMetric;
    transitionsWithIntent: UxCoverageMetric;
    interactiveControlsWithIntent: UxCoverageMetric;
    errorStatesWithRecovery: UxCoverageMetric;
    criticalGoalsWithScenario: UxCoverageMetric;
  };
  findings: UxValidationFinding[];
  graphSummary: {
    screens: number;
    states: number;
    transitions: number;
    controls: number;
    goals: number;
    scenarios: number;
  };
  scenarioResults?: UxScenarioResult[];
}

export function computeUxCoverage(graph: ProjectUxGraph): ProjectUxAnalysisReport['coverage'] {
  const initialSet = new Set(initialStateIds(graph));
  const errorStates = graph.states.filter((s) => s.role === 'error');
  const errorStatesCovered = errorStates.filter((s) => {
    if (hasPathTo(graph, s.stateId, initialSet)) return true;
    return Boolean(s.meta.recoveryStateId) && hasPathTo(graph, s.stateId, new Set([s.meta.recoveryStateId!]));
  });
  const criticalGoals = graph.goals.filter((g) => g.criticality === 'destructive' || g.criticality === 'critical');
  const criticalGoalsCovered = criticalGoals.filter((g) => graph.scenarios.some((s) => s.goalId === g.id));

  return {
    screensWithRole: { covered: graph.screens.filter((s) => s.role !== 'unknown').length, total: graph.screens.length },
    statesWithPurpose: { covered: graph.states.filter((s) => Boolean(s.meta.purpose)).length, total: graph.states.length },
    transitionsWithIntent: { covered: graph.transitions.filter((t) => Boolean(t.intent)).length, total: graph.transitions.length },
    interactiveControlsWithIntent: { covered: graph.controls.filter((c) => Boolean(c.intent)).length, total: graph.controls.length },
    errorStatesWithRecovery: { covered: errorStatesCovered.length, total: errorStates.length },
    criticalGoalsWithScenario: { covered: criticalGoalsCovered.length, total: criticalGoals.length }
  };
}

function computeSummary(findings: readonly UxValidationFinding[]): ProjectUxAnalysisReport['summary'] {
  const summary = { errors: 0, warnings: 0, infos: 0, suggestions: 0, needsHumanReview: 0 };
  for (const finding of findings) {
    if (finding.severity === 'error') summary.errors += 1;
    else if (finding.severity === 'warning') summary.warnings += 1;
    else if (finding.severity === 'info') summary.infos += 1;
    else if (finding.severity === 'suggestion') summary.suggestions += 1;
    else if (finding.severity === 'needs_human_review') summary.needsHumanReview += 1;
  }
  return summary;
}

function computeVerdict(deterministic: readonly UxValidationFinding[], heuristic: readonly UxValidationFinding[]): ProjectUxAnalysisReport['verdict'] {
  if (deterministic.some((f) => f.severity === 'error')) return 'fail';
  const needsReview = deterministic.some((f) => f.severity === 'warning' || f.severity === 'needs_human_review') || heuristic.length > 0;
  return needsReview ? 'needs_review' : 'pass';
}

export async function analyzeProjectUx(
  project: LcdBitmapProject,
  options: ProjectUxAnalysisOptions = {}
): Promise<ProjectUxAnalysisReport> {
  const graph = buildProjectUxGraph(project);

  let scenarioResults: UxScenarioResult[] | undefined;
  if (options.includeScenarioExecution) {
    const scenarios = options.scenarioIds
      ? graph.scenarios.filter((s) => options.scenarioIds!.includes(s.id))
      : graph.scenarios;
    scenarioResults = await Promise.all(scenarios.map((scenario) => runUxScenario(project, scenario)));
  }

  const deterministic: UxValidationFinding[] = [
    ...evaluateStructureRules(graph),
    ...evaluateNavigationRules(graph),
    ...evaluateSemanticsRules(graph),
    ...evaluateSafetyRules(graph),
    ...evaluateScenarioRules(graph, scenarioResults ?? [])
  ];
  if (options.includeVisualChecks) {
    deterministic.push(...evaluateVisualChecks(project, graph));
  }

  const heuristic = options.heuristicFindings ?? [];
  const findings = sortFindings([...deterministic, ...heuristic]);

  return {
    version: 1,
    verdict: computeVerdict(deterministic, heuristic),
    generatedAt: new Date().toISOString(),
    summary: computeSummary(findings),
    coverage: computeUxCoverage(graph),
    findings,
    graphSummary: {
      screens: graph.screens.length,
      states: graph.states.length,
      transitions: graph.transitions.length,
      controls: graph.controls.length,
      goals: graph.goals.length,
      scenarios: graph.scenarios.length
    },
    scenarioResults
  };
}
