/**
 * Rust embedded-graphics export backend.
 *
 * Produces a Rust source file with a const byte array compatible with
 * the embedded-graphics crate's ImageRaw type.
 *
 * Generated file usage:
 *   mod screens;
 *   use embedded_graphics::{image::ImageRaw, pixelcolor::BinaryColor, prelude::*};
 *
 *   let img = ImageRaw::<BinaryColor>::new(&screens::SCREEN_NAME, screens::SCREEN_NAME_WIDTH);
 *   Image::new(&img, Point::zero()).draw(&mut display)?;
 *
 * Compatible: embedded-graphics 0.8+, embassy, RTIC, rp-hal, stm32-hal, nrf-hal.
 */

import { createCodegenArtifact, createCodegenArtifactSet } from '../artifacts/codegenArtifacts';
import type { LoweredScreenIr, LoweredTargetIrV1 } from '../target-ir/targetIr';
import type { CodegenBackend, CodegenRequest } from './codegenBackend';
import { sanitizeSymbolName } from './legacyCBackend';

export const RUST_BACKEND_ID = 'rust-embedded-backend';
const BYTES_PER_ROW = 16;

export const rustBackend: CodegenBackend = {
  id: RUST_BACKEND_ID,
  targetProfileId: 'legacy-lcd-vertical-lsb',
  generate(targetIr, request) {
    const { width, height } = targetIr.targetProfile.display;

    if (request.scope === 'selected-screen') {
      const screen = requireSelectedScreen(targetIr, request.selectedScreenId);
      const sym = sanitizeSymbolName(request.selectedSymbolName ?? `${screen.id}_screen`).toUpperCase();
      const source = createCodegenArtifact(
        'c-header',
        `${screen.id}_screen.rs`,
        'text/x-rust',
        generateSingleScreenRs(sym, screen.framebufferBytes, width, height)
      );
      return createCodegenArtifactSet(RUST_BACKEND_ID, targetIr.targetProfile.id, targetIr.sourceFingerprint, [source]);
    }

    const baseName = sanitizeSymbolName(request.projectSymbolName ?? targetIr.project.id);
    const source = createCodegenArtifact(
      'c-header',
      `${baseName}_lcd_screens.rs`,
      'text/x-rust',
      generateAllScreensRs(baseName, targetIr)
    );
    return createCodegenArtifactSet(RUST_BACKEND_ID, targetIr.targetProfile.id, targetIr.sourceFingerprint, [source]);
  }
};

function generateSingleScreenRs(sym: string, bytes: readonly number[], width: number, height: number): string {
  const rows = chunkBytes(bytes, BYTES_PER_ROW).map(
    (row) => '    ' + row.map((b) => `0x${b.toString(16).padStart(2, '0')}`).join(', ')
  );
  return [
    `//! LCD bitmap — 1bpp vertical-page LSB (SSD1306 native)`,
    `//! Dimensions: ${width}×${height} px  |  ${bytes.length} bytes`,
    `//!`,
    `//! Usage:`,
    `//!   use embedded_graphics::{image::ImageRaw, pixelcolor::BinaryColor, prelude::*};`,
    `//!   let img = ImageRaw::<BinaryColor>::new(&${sym}, ${sym}_WIDTH);`,
    `//!   Image::new(&img, Point::zero()).draw(&mut display)?;`,
    '',
    `pub const ${sym}_WIDTH: u32 = ${width};`,
    `pub const ${sym}_HEIGHT: u32 = ${height};`,
    '',
    `pub const ${sym}: [u8; ${bytes.length}] = [`,
    rows.join(',\n'),
    '];'
  ].join('\n');
}

function generateAllScreensRs(baseName: string, targetIr: LoweredTargetIrV1): string {
  const { width, height } = targetIr.targetProfile.display;
  const lines: string[] = [
    `//! LCD screen bundle — 1bpp vertical-page LSB (SSD1306 native)`,
    `//! Dimensions: ${width}×${height} px per screen  |  ${targetIr.screens.length} screens`,
    `//!`,
    `//! Generated by LCD-bitmap IDE`,
    `//!`,
    `//! Usage:`,
    `//!   use embedded_graphics::{image::ImageRaw, pixelcolor::BinaryColor, prelude::*};`,
    `//!   let img = ImageRaw::<BinaryColor>::new(SCREENS[0].data, ${baseName.toUpperCase()}_WIDTH);`,
    '',
    `pub const ${baseName.toUpperCase()}_WIDTH: u32 = ${width};`,
    `pub const ${baseName.toUpperCase()}_HEIGHT: u32 = ${height};`,
    `pub const ${baseName.toUpperCase()}_SCREEN_COUNT: usize = ${targetIr.screens.length};`,
    ''
  ];

  for (const screen of targetIr.screens) {
    const sym = sanitizeSymbolName(`${baseName}_${screen.id}_screen`).toUpperCase();
    const rows = chunkBytes(screen.framebufferBytes, BYTES_PER_ROW).map(
      (row) => '    ' + row.map((b) => `0x${b.toString(16).padStart(2, '0')}`).join(', ')
    );
    lines.push(
      `/// FSM state: "${screen.id}"`,
      `pub const ${sym}: [u8; ${screen.framebufferBytes.length}] = [`,
      rows.join(',\n'),
      '];',
      ''
    );
  }

  // Lookup table (state_id → &[u8])
  const tableRows = targetIr.screens.map((screen) => {
    const sym = sanitizeSymbolName(`${baseName}_${screen.id}_screen`).toUpperCase();
    return `    LcdScreenEntry { state_id: "${screen.id}", data: &${sym} }`;
  });
  lines.push(
    `pub struct LcdScreenEntry {`,
    `    pub state_id: &'static str,`,
    `    pub data: &'static [u8],`,
    `}`,
    '',
    `pub static SCREENS: [LcdScreenEntry; ${targetIr.screens.length}] = [`,
    tableRows.join(',\n'),
    '];'
  );

  return lines.join('\n');
}

function chunkBytes(bytes: readonly number[], size: number): number[][] {
  const chunks: number[][] = [];
  for (let i = 0; i < bytes.length; i += size) {
    chunks.push([...bytes.slice(i, i + size)]);
  }
  return chunks;
}

function requireSelectedScreen(targetIr: LoweredTargetIrV1, selectedScreenId: string | undefined): LoweredScreenIr {
  const screen = targetIr.screens.find((s) => s.id === selectedScreenId) ?? targetIr.screens[0];
  if (!screen) throw new Error('No LCD screen available for Rust export');
  return screen;
}
