/**
 * Stable diagnostic codes for Screen DSL file operations.
 * These codes appear in ScreenDslFileDiagnostic.code and must not change
 * across releases (they may be stored in project logs or shown in UI).
 */

export const SCREEN_DSL_FILE_UNSUPPORTED_EXTENSION = 'SCREEN_DSL_FILE_UNSUPPORTED_EXTENSION';
export const SCREEN_DSL_FILE_TOO_LARGE = 'SCREEN_DSL_FILE_TOO_LARGE';
export const SCREEN_DSL_FILE_INVALID_UTF8 = 'SCREEN_DSL_FILE_INVALID_UTF8';
export const SCREEN_DSL_FILE_UTF16_UNSUPPORTED = 'SCREEN_DSL_FILE_UTF16_UNSUPPORTED';
export const SCREEN_DSL_FILE_BINARY_CONTENT = 'SCREEN_DSL_FILE_BINARY_CONTENT';
export const SCREEN_DSL_FILE_EMPTY = 'SCREEN_DSL_FILE_EMPTY';
export const SCREEN_DSL_FILE_READ_FAILED = 'SCREEN_DSL_FILE_READ_FAILED';
export const SCREEN_DSL_FILE_WRITE_FAILED = 'SCREEN_DSL_FILE_WRITE_FAILED';
export const SCREEN_DSL_FILE_RENAME_FAILED = 'SCREEN_DSL_FILE_RENAME_FAILED';
export const SCREEN_DSL_FILE_INVALID_NAME = 'SCREEN_DSL_FILE_INVALID_NAME';
export const SCREEN_DSL_FILE_NAME_NORMALIZED = 'SCREEN_DSL_FILE_NAME_NORMALIZED';
export const SCREEN_DSL_FILE_FORMAT_EXTENSION_MISMATCH = 'SCREEN_DSL_FILE_FORMAT_EXTENSION_MISMATCH';
export const SCREEN_DSL_FILE_INVALID_IPC_PAYLOAD = 'SCREEN_DSL_FILE_INVALID_IPC_PAYLOAD';
export const SCREEN_DSL_FILE_INTERNAL_ERROR = 'SCREEN_DSL_FILE_INTERNAL_ERROR';
export const SCREEN_DSL_FILE_IS_DIRECTORY = 'SCREEN_DSL_FILE_IS_DIRECTORY';
export const SCREEN_DSL_FILE_NUL_BYTES = 'SCREEN_DSL_FILE_NUL_BYTES';
